Repository Na-o-man/Na-o-man_server, pull requests merged in 2024-08, with the labels that each got.

#39 [FIX] 사진 조회 API 반환값 수정
  src/main/java/com/umc/naoman/domain/photo/converter/PhotoConverter.java
  src/main/java/com/umc/naoman/domain/photo/dto/PhotoResponse.java
Labels: :bug:fix

#43 [FEAT] ShareGroup 조회 API 구현
  src/main/java/com/umc/naoman/domain/shareGroup/controller/ShareGroupController.java
  src/main/java/com/umc/naoman/domain/shareGroup/converter/ShareGroupConverter.java
  src/main/java/com/umc/naoman/domain/shareGroup/dto/ShareGroupRequest.java
  src/main/java/com/umc/naoman/domain/shareGroup/dto/ShareGroupResponse.java
  src/main/java/com/umc/naoman/domain/shareGroup/repository/ProfileRepository.java
  src/main/java/com/umc/naoman/domain/shareGroup/repository/ShareGroupRepository.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupService.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupServiceImpl.java
  src/main/java/com/umc/naoman/global/result/code/ShareGroupResultCode.java
Labels: :sparkles:feature

#41 [FEAT] 특정 사진 삭제 API 구현
  src/main/java/com/umc/naoman/domain/photo/controller/PhotoController.java
  src/main/java/com/umc/naoman/domain/photo/converter/PhotoConverter.java
  src/main/java/com/umc/naoman/domain/photo/dto/PhotoRequest.java
  src/main/java/com/umc/naoman/domain/photo/dto/PhotoResponse.java
  src/main/java/com/umc/naoman/domain/photo/repository/PhotoRepository.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoService.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
  src/main/java/com/umc/naoman/domain/shareGroup/repository/ProfileRepository.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupService.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupServiceImpl.java
  src/main/java/com/umc/naoman/global/error/code/S3ErrorCode.java
  src/main/java/com/umc/naoman/global/result/code/PhotoResultCode.java
Labels: :sparkles:feature

#44 [FIX] 회원가입 시 temp-member-info 값 전달 방식 변경 #42
  src/main/java/com/umc/naoman/domain/member/controller/AuthController.java
  src/main/java/com/umc/naoman/global/error/code/MemberErrorCode.java
Labels: :bug:fix

#46 [FEAT] 공유그룹 삭제 API 구현
  src/main/java/com/umc/naoman/domain/shareGroup/controller/ShareGroupController.java
  src/main/java/com/umc/naoman/domain/shareGroup/converter/ShareGroupConverter.java
  src/main/java/com/umc/naoman/domain/shareGroup/entity/ShareGroup.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupService.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupServiceImpl.java
  src/main/java/com/umc/naoman/global/error/code/ShareGroupErrorCode.java
  src/main/java/com/umc/naoman/global/result/code/ShareGroupResultCode.java
Labels: :sparkles:feature

#51 [FEAT] 내 공유 그룹 초대 코드 조회 API 구현
  src/main/java/com/umc/naoman/domain/shareGroup/controller/ShareGroupController.java
  src/main/java/com/umc/naoman/domain/shareGroup/converter/ShareGroupConverter.java
  src/main/java/com/umc/naoman/domain/shareGroup/dto/ShareGroupRequest.java
  src/main/java/com/umc/naoman/domain/shareGroup/dto/ShareGroupResponse.java
  src/main/java/com/umc/naoman/domain/shareGroup/repository/ProfileRepository.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupService.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupServiceImpl.java
  src/main/java/com/umc/naoman/global/error/code/ShareGroupErrorCode.java
  src/main/java/com/umc/naoman/global/result/code/ShareGroupResultCode.java
Labels: :sparkles:feature

#53 docs : 사진 관련 API Swagger를 활용히여 문서화
  src/main/java/com/umc/naoman/domain/photo/controller/PhotoController.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
Labels: :memo:docs

#60 [FEAT] 내 회원정보 조회 구현, 인증되지 않은 사용자의 요청 별도 처리 플로우 구현
  src/main/java/com/umc/naoman/domain/member/controller/MemberController.java
  src/main/java/com/umc/naoman/domain/member/service/MemberService.java
  src/main/java/com/umc/naoman/domain/member/service/MemberServiceImpl.java
  src/main/java/com/umc/naoman/global/error/code/GlobalErrorCode.java
  src/main/java/com/umc/naoman/global/security/SecurityConfig.java
  src/main/java/com/umc/naoman/global/security/handler/CustomAuthenticationEntryPoint.java
Labels: :sparkles:feature

#57 [FEAT] 사진 다운로드 API 구현
  src/main/java/com/umc/naoman/domain/photo/controller/PhotoController.java
  src/main/java/com/umc/naoman/domain/photo/converter/PhotoConverter.java
  src/main/java/com/umc/naoman/domain/photo/dto/PhotoResponse.java
  src/main/java/com/umc/naoman/domain/photo/repository/PhotoRepository.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoService.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
  src/main/java/com/umc/naoman/global/error/code/S3ErrorCode.java
  src/main/java/com/umc/naoman/global/result/ResultResponse.java
  src/main/java/com/umc/naoman/global/result/code/PhotoResultCode.java
Labels: :sparkles:feature

#55 [FEAT] 엘라스틱서치 기본 설정 및 사진 저장, 조희 repository 구현
  build.gradle
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/document/FaceVector.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/document/PhotoEs.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/document/SampleFaceVector.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/index/face_vectors.json
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/index/photos_es.json
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/index/sample_photo_vectors.json
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/FaceVectorRepository.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/PhotoEsClientRepository.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/PhotoEsRepository.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/SampleFaceVectorRepository.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/service/PhotoEsService.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/service/PhotoEsServiceImpl.java
  src/main/java/com/umc/naoman/global/config/ElasticsearchConfig.java
  src/main/java/com/umc/naoman/global/error/BusinessException.java
  src/main/java/com/umc/naoman/global/error/code/ElasticsearchErrorCode.java
Labels: :sparkles:feature

#48 [FEAT] 새 안건 추가 API 구현
  src/main/java/com/umc/naoman/domain/agenda/controller/AgendaController.java
  src/main/java/com/umc/naoman/domain/agenda/converter/AgendaConverter.java
  src/main/java/com/umc/naoman/domain/agenda/converter/AgendaPhotoConverter.java
  src/main/java/com/umc/naoman/domain/agenda/dto/AgendaRequest.java
  src/main/java/com/umc/naoman/domain/agenda/dto/AgendaResponse.java
  src/main/java/com/umc/naoman/domain/agenda/entity/Agenda.java
  src/main/java/com/umc/naoman/domain/agenda/entity/AgendaPhoto.java
  src/main/java/com/umc/naoman/domain/agenda/repository/AgendaPhotoRepository.java
  src/main/java/com/umc/naoman/domain/agenda/repository/AgendaRepository.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaPhotoService.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaPhotoServiceImpl.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaService.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaServiceImpl.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoService.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupServiceImpl.java
  src/main/java/com/umc/naoman/global/error/code/AgendaErrorCode.java
  src/main/java/com/umc/naoman/global/error/code/PhotoErrorCode.java
  src/main/java/com/umc/naoman/global/result/code/AgendaResultCode.java
Labels: :sparkles:feature

#65 [REFACTOR] 공유 그룹 스웨거에 설명 추가
  src/main/java/com/umc/naoman/domain/shareGroup/controller/ShareGroupController.java
Labels: :recycle:refactor

#63 [FEAT] GPT 프롬프트로 공유그룹 이름 생성, 회원의 프로필 목록 조회 로직 구현
  build.gradle
  src/main/java/com/umc/naoman/domain/shareGroup/controller/ShareGroupController.java
  src/main/java/com/umc/naoman/domain/shareGroup/converter/ShareGroupConverter.java
  src/main/java/com/umc/naoman/domain/shareGroup/entity/Profile.java
  src/main/java/com/umc/naoman/domain/shareGroup/entity/ShareGroup.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/OpenAiService.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/OpenAiServiceImpl.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupService.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupServiceImpl.java
Labels: :sparkles:feature

#67 [FIX] 회원가입 여부 판별하는 로직 변경, buid.gradle 간소화
  build.gradle
  src/main/java/com/umc/naoman/domain/member/controller/AuthController.java
  src/main/java/com/umc/naoman/domain/member/repository/MemberRepository.java
  src/main/java/com/umc/naoman/domain/member/service/MemberService.java
  src/main/java/com/umc/naoman/domain/member/service/MemberServiceImpl.java
  src/main/java/com/umc/naoman/global/security/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/naoman/global/security/model/CustomOAuth2User.java
Labels: :bug:fix, :recycle:refactor

#62 [FEAT] 알림 컨트롤러에 스웨거 추가
  src/main/java/com/umc/naoman/domain/notification/controller/NotificationController.java
  src/main/java/com/umc/naoman/domain/notification/converter/NotificationConverter.java
  src/main/java/com/umc/naoman/domain/notification/dto/NotificationResponse.java
  src/main/java/com/umc/naoman/domain/notification/service/FcmService.java
  src/main/java/com/umc/naoman/domain/notification/service/FcmServiceImpl.java
Labels: :sparkles:feature

#71 [FEAT] 투표하기 및 특정 안건의 투표 현황 조회 API 구현, 자잘한 api 관련 수정
  src/main/java/com/umc/naoman/domain/agenda/controller/AgendaController.java
  src/main/java/com/umc/naoman/domain/agenda/repository/AgendaPhotoRepository.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaPhotoService.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaPhotoServiceImpl.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaService.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaServiceImpl.java
  src/main/java/com/umc/naoman/domain/member/controller/AuthController.java
  src/main/java/com/umc/naoman/domain/member/controller/MemberController.java
  src/main/java/com/umc/naoman/domain/member/service/MemberService.java
  src/main/java/com/umc/naoman/domain/member/service/MemberServiceImpl.java
  src/main/java/com/umc/naoman/domain/notification/controller/NotificationController.java
  src/main/java/com/umc/naoman/domain/photo/controller/PhotoController.java
  src/main/java/com/umc/naoman/domain/shareGroup/controller/ShareGroupController.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupService.java
  src/main/java/com/umc/naoman/domain/vote/controller/VoteController.java
  src/main/java/com/umc/naoman/domain/vote/converter/VoteConverter.java
  src/main/java/com/umc/naoman/domain/vote/dto/VoteRequest.java
  src/main/java/com/umc/naoman/domain/vote/dto/VoteResponse.java
  src/main/java/com/umc/naoman/domain/vote/entity/Vote.java
  src/main/java/com/umc/naoman/domain/vote/repository/VoteRepository.java
  src/main/java/com/umc/naoman/domain/vote/service/VoteService.java
  src/main/java/com/umc/naoman/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/umc/naoman/global/error/code/AgendaErrorCode.java
  src/main/java/com/umc/naoman/global/error/code/VoteErrorCode.java
  src/main/java/com/umc/naoman/global/result/code/MemberResultCode.java
  src/main/java/com/umc/naoman/global/result/code/VoteResultCode.java
Labels: :sparkles:feature, :memo:docs, :bug:fix

#75 [FEAT] 안건 관련 API 구현
  src/main/java/com/umc/naoman/domain/agenda/controller/AgendaController.java
  src/main/java/com/umc/naoman/domain/agenda/converter/AgendaConverter.java
  src/main/java/com/umc/naoman/domain/agenda/converter/AgendaPhotoConverter.java
  src/main/java/com/umc/naoman/domain/agenda/dto/AgendaPhotoResponse.java
  src/main/java/com/umc/naoman/domain/agenda/dto/AgendaRequest.java
  src/main/java/com/umc/naoman/domain/agenda/dto/AgendaResponse.java
  src/main/java/com/umc/naoman/domain/agenda/entity/Agenda.java
  src/main/java/com/umc/naoman/domain/agenda/entity/AgendaPhoto.java
  src/main/java/com/umc/naoman/domain/agenda/repository/AgendaRepository.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaService.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaServiceImpl.java
  src/main/java/com/umc/naoman/domain/shareGroup/entity/Profile.java
  src/main/java/com/umc/naoman/domain/shareGroup/entity/ShareGroup.java
  src/main/java/com/umc/naoman/domain/vote/entity/Vote.java
  src/main/java/com/umc/naoman/domain/vote/repository/VoteRepository.java
  src/main/java/com/umc/naoman/domain/vote/service/VoteServiceImpl.java
  src/main/java/com/umc/naoman/global/result/code/AgendaResultCode.java
  src/main/java/com/umc/naoman/global/security/util/CookieUtils.java
Labels: :sparkles:feature

#70 [FEAT] 사진 업로드 때, 새로운 맴버가 그룹에 들어갈 때, 얼굴 인식 로직
  build.gradle
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/document/FaceVector.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/document/PhotoEs.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/document/SampleFaceVector.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/index/face_vectors.json
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/index/photos_es.json
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/index/sample_photo_vectors.json
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/FaceVectorRepository.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/PhotoEsClientRepository.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/PhotoEsRepository.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/SampleFaceVectorRepository.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/service/PhotoEsService.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/service/PhotoEsServiceImpl.java
  src/main/java/com/umc/naoman/domain/photo/service/FaceDetectionService.java
  src/main/java/com/umc/naoman/domain/photo/service/FaceDetectionServiceImpl.java
  src/main/java/com/umc/naoman/global/config/AsyncConfig.java
  src/main/java/com/umc/naoman/global/config/AwsConfig.java
  src/main/java/com/umc/naoman/global/error/code/AwsLambdaErrorCode.java
Labels: :sparkles:feature

#78 [FEAT] 특정 공유그룹의 아무도 인식되지 않은 사진 조회 API 구현
  src/main/java/com/umc/naoman/domain/photo/controller/PhotoController.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/service/PhotoEsService.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/service/PhotoEsServiceImpl.java
Labels: :sparkles:feature

#80 [FIX] Elasticsearch 벌크 저장, 얼굴 인식 서비스 호출
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
  src/main/java/com/umc/naoman/global/error/code/S3ErrorCode.java
Labels: :bug:fix

#82 [FIX] 사진 업로드, 조회시 발생하는 버그 수정
  src/main/java/com/umc/naoman/domain/photo/converter/PhotoConverter.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
Labels: :bug:fix

#86 [FIX] 삭제 로직 벌크 삭제로 수정
  src/main/java/com/umc/naoman/domain/photo/repository/PhotoRepository.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
Labels: :bug:fix

#91 [Feat] 기존 서비스 공유그룹 참여 서비스 로직에서 새로 참여한 맴버의 얼굴을 인식하는 로직 추가
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupServiceImpl.java
Labels: :sparkles:feature

#92 [FEAT] 샘플 이미지 업로드 API 구현, 이외 사진 도메인 리팩토링
  src/main/java/com/umc/naoman/domain/agenda/repository/AgendaPhotoRepository.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaPhotoService.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaPhotoServiceImpl.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaService.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaServiceImpl.java
  src/main/java/com/umc/naoman/domain/member/controller/MemberController.java
  src/main/java/com/umc/naoman/domain/photo/controller/PhotoController.java
  src/main/java/com/umc/naoman/domain/photo/converter/PhotoConverter.java
  src/main/java/com/umc/naoman/domain/photo/converter/SamplePhotoConverter.java
  src/main/java/com/umc/naoman/domain/photo/dto/PhotoRequest.java
  src/main/java/com/umc/naoman/domain/photo/dto/PhotoResponse.java
  src/main/java/com/umc/naoman/domain/photo/repository/SamplePhotoRepository.java
  src/main/java/com/umc/naoman/domain/photo/service/FaceDetectionService.java
  src/main/java/com/umc/naoman/domain/photo/service/FaceDetectionServiceImpl.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoService.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupServiceImpl.java
  src/main/java/com/umc/naoman/global/result/code/PhotoResultCode.java
  src/main/java/com/umc/naoman/global/security/util/CookieUtils.java
Labels: :sparkles:feature, :bug:fix, :recycle:refactor

#88 [FEAT] 엘라스틱서치 사진 삭제 로직 추가
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/FaceVectorClientRepository.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/PhotoEsClientRepository.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/SampleFaceVectorClientRepository.java
  src/test/java/com/umc/naoman/domain/photo/elasticsearch/repository/PhotoEsClientRepositoryTest.java
Labels: :sparkles:feature

#89 [FEAT] 특정 앨범의 사진 전체 다운로드 API 구현
  src/main/java/com/umc/naoman/domain/photo/controller/PhotoController.java
  src/main/java/com/umc/naoman/domain/photo/converter/PhotoConverter.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/PhotoEsClientRepository.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/service/PhotoEsService.java
  src/main/java/com/umc/naoman/domain/photo/repository/PhotoRepository.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoService.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
Labels: :sparkles:feature

#96 [FIX] 사진 삭제 로직 수정
  src/main/java/com/umc/naoman/domain/photo/service/PhotoService.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
Labels: :bug:fix

#101 [FEAT] 아무도 인식되지 않은 사진 전체 다운로드 API 구현
  src/main/java/com/umc/naoman/domain/photo/controller/PhotoController.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoService.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
Labels: :sparkles:feature

#107 [FIX] jwt 토큰 처리 관련 예외 핸들링 구현, 회원 식별 방식 변경
  src/main/java/com/umc/naoman/domain/member/repository/MemberRepository.java
  src/main/java/com/umc/naoman/domain/member/service/MemberServiceImpl.java
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/index/sample_face_vectors.json
  src/main/java/com/umc/naoman/global/error/ErrorResponse.java
  src/main/java/com/umc/naoman/global/error/code/JwtErrorCode.java
  src/main/java/com/umc/naoman/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/umc/naoman/global/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/umc/naoman/global/security/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/naoman/global/security/service/MemberDetailsService.java
  src/main/java/com/umc/naoman/global/security/util/JwtUtils.java
Labels: :bug:fix

#111 [Feat] 사진 다운로드 시, photos_es에 다운로드 멤버 아이디 추가
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/PhotoEsClientRepository.java
  src/test/java/com/umc/naoman/domain/photo/elasticsearch/repository/PhotoEsClientRepositoryTest.java
Labels: :sparkles:feature

#110 [FEAT] 회원 탈퇴시 필요한 사진 삭제 함수 구현
  src/main/java/com/umc/naoman/domain/photo/service/PhotoService.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
Labels: :sparkles:feature

#114 [Refact] : 다운로드 태그 추가 시 사진의 url을 통해 업데이트 함
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/PhotoEsClientRepository.java
Labels: :recycle:refactor

#115 [FEAT] 사진 다운로드시 다운로드 이력 추가 기능 구현
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
Labels: :sparkles:feature

#117 [FEAT] 회원의 샘플 사진을 모두 삭제하는 함수 구현
  src/main/java/com/umc/naoman/domain/photo/repository/SamplePhotoRepository.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoService.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
Labels: :sparkles:feature

#118 [FEAT] 회원 탈퇴 api 구현
  src/main/java/com/umc/naoman/domain/member/controller/MemberController.java
  src/main/java/com/umc/naoman/domain/member/converter/MemberConverter.java
  src/main/java/com/umc/naoman/domain/member/dto/MemberResponse.java
  src/main/java/com/umc/naoman/domain/member/service/MemberService.java
  src/main/java/com/umc/naoman/domain/member/service/MemberServiceImpl.java
  src/main/java/com/umc/naoman/global/result/code/MemberResultCode.java
Labels: :sparkles:feature

#120 [FIX] photos_es 페이지 조회의 결과가 무조건 isLast값이 true인 버그 수정
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/repository/PhotoEsClientRepository.java
Labels: :bug:fix

#122 [FEAT] 쿠키 생성 시 도메인 ".naoman.site"로 설정
  src/main/java/com/umc/naoman/global/security/util/CookieUtils.java
Labels: :sparkles:feature

#125 [FEAT] 성능 이슈가 의심되는 특정 API에 대한 수행 시간 로깅 추가
  src/main/java/com/umc/naoman/domain/photo/controller/PhotoController.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
Labels: :sparkles:feature

#127 [FIX] 탈퇴 시 안건 후보로 등록된 사진 삭제 불가 이슈 해결
  src/main/java/com/umc/naoman/domain/agenda/dto/AgendaResponse.java
  src/main/java/com/umc/naoman/domain/agenda/entity/AgendaPhoto.java
  src/main/java/com/umc/naoman/domain/agenda/repository/AgendaPhotoRepository.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaPhotoService.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaPhotoServiceImpl.java
  src/main/java/com/umc/naoman/domain/agenda/service/AgendaServiceImpl.java
  src/main/java/com/umc/naoman/domain/member/service/MemberServiceImpl.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoQueryService.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoQueryServiceImpl.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoService.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
Labels: :bug:fix

#128 fix: 누락된 함수 호출 로직 추가
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
Labels: :bug:fix

#130 [FEAT] 공유 그룹의 대표 이미지를 초기화하는 로직 추가
  src/main/java/com/umc/naoman/domain/photo/elasticsearch/service/PhotoEsServiceImpl.java
  src/main/java/com/umc/naoman/domain/shareGroup/entity/ShareGroup.java
Labels: :sparkles:feature

#134 [FIX] 이미 존재하는 프로필에 참여 못하게 하는 로직
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupServiceImpl.java
  src/main/java/com/umc/naoman/global/error/code/ShareGroupErrorCode.java
  src/main/java/com/umc/naoman/global/security/util/CookieUtils.java
Labels: :bug:fix

#133 [FEAT] 특정 공유그룹 사진 전체 다운로드 API 구현
  src/main/java/com/umc/naoman/domain/photo/controller/PhotoController.java
  src/main/java/com/umc/naoman/domain/photo/repository/PhotoRepository.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoService.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
Labels: :sparkles:feature
