Repository Na-o-man/Na-o-man_server, pull requests merged in 2024-07, with the labels that each got.

#3 [FEAT] Member 도메인 관련 파일 생성 및 기본 함수 구현
  src/main/java/com/umc/naoman/domain/member/converter/MemberConverter.java
  src/main/java/com/umc/naoman/domain/member/repository/MemberRepository.java
  src/main/java/com/umc/naoman/domain/member/service/MemberService.java
  src/main/java/com/umc/naoman/domain/member/service/MemberServiceImpl.java
Labels: :sparkles:feature

#19 [FEAT] OAuth 방식의 소셜 로그인/회원가입 구현, 스웨거 세팅
  build.gradle
  src/main/java/com/umc/naoman/NaomanApplication.java
  src/main/java/com/umc/naoman/domain/member/controller/AuthController.java
  src/main/java/com/umc/naoman/domain/member/controller/MemberController.java
  src/main/java/com/umc/naoman/domain/member/converter/MemberConverter.java
  src/main/java/com/umc/naoman/domain/member/dto/MemberRequest.java
  src/main/java/com/umc/naoman/domain/member/dto/MemberResponse.java
  src/main/java/com/umc/naoman/domain/member/entity/Member.java
  src/main/java/com/umc/naoman/domain/member/entity/SocialType.java
  src/main/java/com/umc/naoman/domain/member/entity/redis/RefreshToken.java
  src/main/java/com/umc/naoman/domain/member/repository/MemberRepository.java
  src/main/java/com/umc/naoman/domain/member/repository/redis/RefreshTokenRepository.java
  src/main/java/com/umc/naoman/domain/member/service/MemberService.java
  src/main/java/com/umc/naoman/domain/member/service/MemberServiceImpl.java
  src/main/java/com/umc/naoman/domain/member/service/redis/RefreshTokenService.java
  src/main/java/com/umc/naoman/domain/member/service/redis/RefreshTokenServiceImpl.java
  src/main/java/com/umc/naoman/global/config/SwaggerConfig.java
  src/main/java/com/umc/naoman/global/error/code/MemberErrorCode.java
  src/main/java/com/umc/naoman/global/result/code/MemberResultCode.java
  src/main/java/com/umc/naoman/global/security/SecurityConfig.java
  src/main/java/com/umc/naoman/global/security/annotation/LoginMember.java
  src/main/java/com/umc/naoman/global/security/attribute/OAuthAttribute.java
  src/main/java/com/umc/naoman/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/umc/naoman/global/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/umc/naoman/global/security/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/naoman/global/security/model/CustomOAuth2User.java
  src/main/java/com/umc/naoman/global/security/model/MemberDetails.java
  src/main/java/com/umc/naoman/global/security/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/umc/naoman/global/security/service/CustomOAuth2UserService.java
  src/main/java/com/umc/naoman/global/security/service/MemberDetailsService.java
  src/main/java/com/umc/naoman/global/security/util/CookieUtils.java
  src/main/java/com/umc/naoman/global/security/util/JwtUtils.java
Labels: :sparkles:feature

#22 [FEAT] 특정 회원 정보 조회 api
  src/main/java/com/umc/naoman/domain/member/controller/MemberController.java
  src/main/java/com/umc/naoman/domain/member/converter/MemberConverter.java
  src/main/java/com/umc/naoman/domain/member/dto/MemberResponse.java
  src/main/java/com/umc/naoman/global/result/code/MemberResultCode.java
Labels: :sparkles:feature

#24 [CHORE] CI/CD 세팅, Swagger 제목, 설명 변경
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md
  .github/workflows/cicd-dev.yml
  Dockerfile
  build.gradle
  compose.yml
  src/main/java/com/umc/naoman/global/config/SwaggerConfig.java
Labels: :memo:docs, :construction_worker:cicd

#27 [FIX] @LoginMember 관련 동작 에러 해결
  src/main/java/com/umc/naoman/global/security/model/MemberDetails.java
Labels: :bug:fix

#34 [FIX] 프로필 이미지 컬럼 크기 변경, 약관 동의화면 경로 변경, CORS 설정
  src/main/java/com/umc/naoman/NaomanApplication.java
  src/main/java/com/umc/naoman/domain/member/controller/AuthController.java
  src/main/java/com/umc/naoman/domain/member/dto/MemberRequest.java
  src/main/java/com/umc/naoman/domain/member/entity/Member.java
  src/main/java/com/umc/naoman/domain/shareGroup/entity/Profile.java
  src/main/java/com/umc/naoman/global/config/SwaggerConfig.java
  src/main/java/com/umc/naoman/global/config/WebMvcConfig.java
  src/main/java/com/umc/naoman/global/security/handler/OAuth2LoginSuccessHandler.java
Labels: :bug:fix

#32 [FEAT] 공유그룹 참여 api 구현
  src/main/java/com/umc/naoman/domain/shareGroup/controller/ShareGroupController.java
  src/main/java/com/umc/naoman/domain/shareGroup/converter/ShareGroupConverter.java
  src/main/java/com/umc/naoman/domain/shareGroup/dto/ShareGroupRequest.java
  src/main/java/com/umc/naoman/domain/shareGroup/dto/ShareGroupResponse.java
  src/main/java/com/umc/naoman/domain/shareGroup/entity/Profile.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupService.java
  src/main/java/com/umc/naoman/domain/shareGroup/service/ShareGroupServiceImpl.java
  src/main/java/com/umc/naoman/global/error/code/ShareGroupErrorCode.java
  src/main/java/com/umc/naoman/global/result/code/ShareGroupResultCode.java
Labels: :sparkles:feature

#37 [FEAT] profile 필드 오류 해결
  src/main/java/com/umc/naoman/domain/shareGroup/controller/ShareGroupController.java
  src/main/java/com/umc/naoman/domain/shareGroup/entity/Profile.java
Labels: :bug:fix

#30 [FEAT] 특정 공유 그룹의 전체 사진 조회 API 구현
  src/main/java/com/umc/naoman/domain/photo/controller/PhotoController.java
  src/main/java/com/umc/naoman/domain/photo/converter/PhotoConverter.java
  src/main/java/com/umc/naoman/domain/photo/dto/PhotoResponse.java
  src/main/java/com/umc/naoman/domain/photo/repository/PhotoRepository.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoService.java
  src/main/java/com/umc/naoman/domain/photo/service/PhotoServiceImpl.java
  src/main/java/com/umc/naoman/global/result/code/PhotoResultCode.java
Labels: :sparkles:feature
